const ADD_FAVORITES = "ADD_FAVORITES";
const DELETE_FAVORITES = "DELETE_FAVORITES";
const SUCCESSFULL = "SUCCESSFULL";
const ERROR = "ERROR";
const ADD_SEEN_LIST = "ADD_SEEN_LIST";
const DELETE_SEEN_LIST = "DELETE_SEEN_LIST";

export {
  ADD_FAVORITES,
  DELETE_FAVORITES,
  SUCCESSFULL,
  ERROR,
  ADD_SEEN_LIST,
  DELETE_SEEN_LIST,
};
